name: Backend CI

on:
  push:
    branches: [ "develop", "main" ]
  pull_request:
    branches: [ "develop", "main" ]

jobs:
  lint-python:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend # Ensure commands run in backend context if requirements.txt is there
    steps:
    - name: Check out code
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10' # Choose your project's Python version
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        # If you have a requirements-dev.txt or similar for linters:
        # pip install -r requirements-dev.txt
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
